version: '3'

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
      - SLACK_SIGNING_SECRET=xxxxxxxxxxxxxxxxx
      - SLACK_BOT_TOKEN=xxxxxxxxxxxxxxxxxx
    volumes:
      - ./src:/usr/src/app
    ports:
      - 3000:3000
